### ISSUE TITLE
Refactor: Cli2Cloud Checklist

### ISSUE THREAD

**Issue by akashchouhan16** [thekaranatic/cli2cloud#6]
**Checklist**
- [x] Updated docs.
- [ ] CI pipeline for builds and tests.
- [x] Env configuration and sample env for project setup.
- [ ] Binary for cli2cloud for v2 release.
- [x] Repository restructure (directories, files, etc)
- [ ] Unit Tests and test pipeline
- [ ] Modular Design

@thekaranatic

**Comment by thekaranatic** [comment]
Hi @akashchouhan16, referring to the check above, I am not much aware about the CI/CD implementation. I would consider doing that if you could help me learn more about it? (resources for example). Else I would consider to drop its implementation for the moment. Thanks

**Comment by akashchouhan16** [comment]
Hey, you could learn to write unit tests for your app! I could guide you to add CI pipelines that could automate the process. It is simple once you implement is once.

For unit tests, there are frameworks that let you do that for Python. If you feel it's not imp at the moment, you could drop it.
Cheers 🥂

**Comment by thekaranatic** [comment]
Sounds great!. I would like to drop it currently and get back to you later to know more about it

**Comment by thekaranatic** [comment]
Hi @akashchouhan16 , I would like you to help me on creating CI pipelines and unit tests for the project

**Comment by akashchouhan16** [comment]
@thekaranatic Sure, happy to assist!
